# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20180117_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='create_by',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='create_by',
        ),
    ]
