# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20180117_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='vote_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='vote_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
