# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20180121_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-create_at']},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
