# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_auto_20180204_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-create_at']},
        ),
    ]
