version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=hasker_user
      - POSTGRES_PASSWORD=hasker_pass
    volumes:
      - db-data:/var/lib/postgresql/data/
  backend:
    build: .
    environment:
      - DB_USER=hasker_user
      - DB_PASSWORD=hasker_pass
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - media:/opt/hasker/media
      - staticfiles:/opt/hasker/staticfiles
volumes:
  db-data:
  media:
  staticfiles:
