# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0004_auto_20180121_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislike_users', models.ManyToManyField(related_name='dislike_answers', to=settings.AUTH_USER_MODEL)),
                ('like_users', models.ManyToManyField(related_name='like_answers', to=settings.AUTH_USER_MODEL)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qa.Answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislike_users', models.ManyToManyField(related_name='dislike_questions', to=settings.AUTH_USER_MODEL)),
                ('like_users', models.ManyToManyField(related_name='like_questions', to=settings.AUTH_USER_MODEL)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qa.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoteModelExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
