# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervote',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_votes', to='qa.Answer'),
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_votes', to='qa.Question'),
        ),
    ]
