# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 13:23
from __future__ import unicode_literals

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/static/img/default/default-avatar-male.png', upload_to=apps.users.models.get_avatar_path),
        ),
    ]
