# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 12:27
from __future__ import unicode_literals

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180204_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to=apps.users.models.get_avatar_path),
        ),
    ]
